Repository hakzzang/Picnic, pull requests merged in 2019-09, with the labels that each got.

#5 closed #3 추천 화면 UI 작업
  app/src/main/java/hbs/com/picnic/data/_EMPTY.kt
  app/src/main/java/hbs/com/picnic/data/model/RecommendMenu.kt
  app/src/main/java/hbs/com/picnic/data/model/_EMPTY.kt
  app/src/main/java/hbs/com/picnic/view/RecommendMenuView.kt
  app/src/main/res/drawable/ic_foodtruck_line.xml
  app/src/main/res/drawable/ic_hanbok_line.xml
  app/src/main/res/drawable/ic_ice_drop_line.xml
  app/src/main/res/drawable/ic_ice_line.xml
  app/src/main/res/drawable/ic_lego_line.xml
  app/src/main/res/drawable/ic_palace_black_line.xml
  app/src/main/res/drawable/ic_palace_green_line.xml
  app/src/main/res/drawable/ic_ricecake_line.xml
  app/src/main/res/drawable/ic_store_line.xml
  app/src/main/res/layout/item_recommend_row.xml
  app/src/main/res/layout/view_recommend_menu.xml
  app/src/main/res/values/strings.xml
Labels: 뷰 구조, 새우버거가 함께 합니다.

#6 closed #4 콘텐츠 화면 UI 개발
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/content/ContentActivity.kt
  app/src/main/java/hbs/com/picnic/view/ContentAdapter.kt
  app/src/main/java/hbs/com/picnic/view/ContentHashTagAdapter.kt
  app/src/main/java/hbs/com/picnic/view/ContentView.kt
  app/src/main/res/layout/activity_content.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_content_content.xml
  app/src/main/res/layout/item_content_subtitle.xml
  app/src/main/res/layout/item_content_title.xml
  app/src/main/res/layout/item_subtitle.xml
  app/src/main/res/layout/layout_coordinator_toolbar.xml
  app/src/main/res/layout/view_content.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 그래들, 뷰 구조, 어렵어렵, 읽어 봤으면 좋겠어요.

#9 closed #7 추천 메뉴 그리드 뷰 개발
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/recommend/_EMPTY.java
  app/src/main/java/hbs/com/picnic/view/RecommendMenuAdapter.kt
  app/src/main/java/hbs/com/picnic/view/RecommendMenuView.kt
  app/src/main/res/drawable/bg_textview_line.xml
  app/src/main/res/layout/activity_recommend.xml
  app/src/main/res/layout/item_recommend_row.xml
  app/src/main/res/layout/view_recommend_menu.xml
Labels: 뷰 구조, 새우버거가 함께 합니다., 초간단

#11 closed #8 백드롭 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/content/_EMPTY.java
  app/src/main/java/hbs/com/picnic/content/adapter/ChattingAdapter.kt
  app/src/main/java/hbs/com/picnic/utils/AnimationUtils.kt
  app/src/main/java/hbs/com/picnic/view/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/ContentViewContract.kt
  app/src/main/java/hbs/com/picnic/view/presenter/ContentViewPresenter.kt
  app/src/main/res/drawable/bg_send_chat_container.xml
  app/src/main/res/drawable/bg_send_chat_off.xml
  app/src/main/res/drawable/bg_send_chat_on.xml
  app/src/main/res/drawable/ic_plug.xml
  app/src/main/res/drawable/ic_send_button_off.xml
  app/src/main/res/drawable/ic_send_button_on.xml
  app/src/main/res/drawable/no_connected_image.xml
  app/src/main/res/drawable/shrimp_burger.png
  app/src/main/res/layout/item_chatting_dialog.xml
  app/src/main/res/layout/layout_bottom_sheet.xml
  app/src/main/res/layout/view_content.xml
  app/src/main/res/mipmap-hdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-mdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xhdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xxxhdpi/ic_your_dialog.9.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 뷰 구조, 어렵어렵

#13 closed #12 지도 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/content/ContentActivity.kt
  app/src/main/java/hbs/com/picnic/content/ContentContract.kt
  app/src/main/java/hbs/com/picnic/content/presenter/ContentPresenter.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ContentUseCase.kt
  app/src/main/java/hbs/com/picnic/remote/MapAPI.kt
  app/src/main/java/hbs/com/picnic/remote/MapRepository.kt
  app/src/main/java/hbs/com/picnic/remote/RetrofitProvider.kt
  app/src/main/java/hbs/com/picnic/remote/_EMPTY.java
  app/src/main/java/hbs/com/picnic/utils/AnimationUtils.kt
  app/src/main/java/hbs/com/picnic/utils/BaseUrl.kt
  app/src/main/java/hbs/com/picnic/view/ContentAdapter.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentAdapter.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentHashTagAdapter.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentViewContract.kt
  app/src/main/java/hbs/com/picnic/view/content/presenter/ContentViewPresenter.kt
  app/src/main/res/layout/activity_content.xml
  app/src/main/res/layout/item_map.xml
  app/src/main/res/layout/layout_coordinator_toolbar.xml
  app/src/main/res/layout/view_content.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/network_security_config.xml
Labels: 그래들, 뷰 구조, 어렵어렵

#15 closed #14 채팅 기능 구현
  app/build.gradle
  app/src/main/java/hbs/com/picnic/content/adapter/ChattingAdapter.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ChattingUseCase.kt
  app/src/main/java/hbs/com/picnic/data/model/ChatMessage.kt
  app/src/main/java/hbs/com/picnic/data/model/_EMPTY.kt
  app/src/main/java/hbs/com/picnic/remote/ChatRepository.kt
  app/src/main/java/hbs/com/picnic/view/content/ChattingDiffUtil.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentViewContract.kt
  app/src/main/java/hbs/com/picnic/view/content/presenter/ContentViewPresenter.kt
  build.gradle
Labels: 그래들, 어렵어렵

#23 closed #21 채팅 기능 상세구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/content/adapter/ChattingAdapter.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ChattingUseCase.kt
  app/src/main/java/hbs/com/picnic/remote/ChatRepository.kt
  app/src/main/java/hbs/com/picnic/view/content/ChattingDiffUtil.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentViewContract.kt
  app/src/main/java/hbs/com/picnic/view/content/presenter/ContentViewPresenter.kt
  app/src/main/res/layout/layout_bottom_sheet.xml
Labels: 기능 추가

#25 closed #24 익명 로그인 기능 추가
  app/build.gradle
  app/src/main/java/hbs/com/picnic/content/ContentActivity.kt
  app/src/main/java/hbs/com/picnic/content/ContentContract.kt
  app/src/main/java/hbs/com/picnic/content/adapter/ChattingAdapter.kt
  app/src/main/java/hbs/com/picnic/content/presenter/ContentPresenter.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ChattingUseCase.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ContentUseCase.kt
  app/src/main/java/hbs/com/picnic/utils/AuthManager.kt
  app/src/main/java/hbs/com/picnic/utils/NicknameManager.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentViewContract.kt
  app/src/main/java/hbs/com/picnic/view/content/presenter/ContentViewPresenter.kt
  app/src/main/res/layout/item_chatting_dialog.xml
  app/src/main/res/layout/item_your_chatting_dialog.xml
  app/src/main/res/mipmap-hdpi/ic_my_dialog.9.png
  app/src/main/res/mipmap-hdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-mdpi/ic_my_dialog.9.png
  app/src/main/res/mipmap-mdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xhdpi/ic_my_dialog.9.png
  app/src/main/res/mipmap-xhdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xxhdpi/ic_my_dialog.9.png
  app/src/main/res/mipmap-xxhdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xxxhdpi/ic_my_dialog.9.png
  app/src/main/res/mipmap-xxxhdpi/ic_your_dialog.9.png
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가, 뷰 구조, 어렵어렵

#26 closed #22 추천 화면 현재 위치 UI 추가 작업
  app/src/main/AndroidManifest.xml
  app/src/main/assets/map_pin_drop.json
  app/src/main/java/hbs/com/picnic/data/model/LocationInfo.kt
  app/src/main/java/hbs/com/picnic/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/recommend/RecommendContract.kt
  app/src/main/java/hbs/com/picnic/recommend/presenter/RecommendPresenter.kt
  app/src/main/java/hbs/com/picnic/recommend/usecase/RecommendUseCase.kt
  app/src/main/java/hbs/com/picnic/remote/MapAPI.kt
  app/src/main/java/hbs/com/picnic/remote/MapRepository.kt
  app/src/main/java/hbs/com/picnic/view/recommend/RecommendMenuView.kt
  app/src/main/java/hbs/com/picnic/view/recommend/adapter/RecommendBottomAdapter.kt
  app/src/main/java/hbs/com/picnic/view/recommend/adapter/RecommendMenuAdapter.kt
  app/src/main/java/hbs/com/picnic/view/recommend/presenter/RecommendViewPresenter.kt
  app/src/main/res/drawable/bg_textview_line.xml
  app/src/main/res/drawable/ic_gps_location.xml
  app/src/main/res/drawable/ic_location_marker.xml
  app/src/main/res/layout/activity_recommend.xml
  app/src/main/res/layout/item_recommend_bottom.xml
  app/src/main/res/layout/item_recommend_row.xml
  app/src/main/res/layout/view_recommend_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens_recommend.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/styles_recommend.xml
Labels: 기능 추가, 뷰 구조, 새우버거가 함께 합니다.

#29 closed #27 채팅 live 기능 및 댓글 갯수 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/content/ContentActivity.kt
  app/src/main/java/hbs/com/picnic/content/adapter/ChattingAdapter.kt
  app/src/main/java/hbs/com/picnic/data/model/CloudMessage.kt
  app/src/main/java/hbs/com/picnic/remote/FcmAPI.kt
  app/src/main/java/hbs/com/picnic/remote/FcmRepository.kt
  app/src/main/java/hbs/com/picnic/remote/MapAPI.kt
  app/src/main/java/hbs/com/picnic/remote/RetrofitProvider.kt
  app/src/main/java/hbs/com/picnic/utils/BaseUrl.kt
  app/src/main/java/hbs/com/picnic/utils/FcmService.kt
  app/src/main/java/hbs/com/picnic/utils/NotificationManager.kt
  app/src/main/java/hbs/com/picnic/utils/ResorceProvider.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/res/layout/layout_bottom_sheet.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#31 closed #30 카카오링크 공유하기 기능 추가
  app/build.gradle
  app/src/main/java/hbs/com/picnic/content/ContentActivity.kt
  app/src/main/java/hbs/com/picnic/utils/KakaoManager.kt
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#32 closed #28 Map의 좌표 검색 기능 추가
  app/src/main/java/hbs/com/picnic/map/MapActivity.kt
  app/src/main/java/hbs/com/picnic/map/MapContract.kt
  app/src/main/java/hbs/com/picnic/map/presenter/MapPresenter.kt
  app/src/main/java/hbs/com/picnic/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/recommend/RecommendContract.kt
  app/src/main/java/hbs/com/picnic/recommend/presenter/RecommendPresenter.kt
  app/src/main/java/hbs/com/picnic/recommend/usecase/RecommendUseCase.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/styles_map.xml
Labels: 기능 추가, 뷰 구조, 새우버거가 함께 합니다.

#35 closed #34 노티피케이션 알림 추가
  app/src/main/java/hbs/com/picnic/content/ContentActivity.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ChattingUseCase.kt
  app/src/main/java/hbs/com/picnic/data/model/CloudMessage.kt
  app/src/main/java/hbs/com/picnic/remote/FcmAPI.kt
  app/src/main/java/hbs/com/picnic/remote/FcmRepository.kt
  app/src/main/java/hbs/com/picnic/utils/BaseUrl.kt
  app/src/main/java/hbs/com/picnic/utils/FcmService.kt
  app/src/main/java/hbs/com/picnic/utils/NotificationUtil.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentViewContract.kt
  app/src/main/java/hbs/com/picnic/view/content/presenter/ContentViewPresenter.kt
Labels: 기능 추가

#37 closed #36 카카오 링크 로직 개선
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 초간단

#39 closed #33 Tour 리스트 API 연동
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/data/model/TourInfo.kt
  app/src/main/java/hbs/com/picnic/data/model/TourRequest.kt
  app/src/main/java/hbs/com/picnic/map/MapActivity.kt
  app/src/main/java/hbs/com/picnic/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/recommend/RecommendContract.kt
  app/src/main/java/hbs/com/picnic/recommend/presenter/RecommendPresenter.kt
  app/src/main/java/hbs/com/picnic/recommend/usecase/RecommendUseCase.kt
  app/src/main/java/hbs/com/picnic/remote/RetrofitProvider.kt
  app/src/main/java/hbs/com/picnic/remote/TourAPI.kt
  app/src/main/java/hbs/com/picnic/remote/TourRepository.kt
  app/src/main/java/hbs/com/picnic/utils/BaseUrl.kt
  app/src/main/java/hbs/com/picnic/utils/CustomItemDecoration.kt
  app/src/main/java/hbs/com/picnic/utils/TourType.kt
  app/src/main/java/hbs/com/picnic/utils/XmlParser.kt
  app/src/main/java/hbs/com/picnic/view/recommend/adapter/RecommendBottomAdapter.kt
  app/src/main/res/layout/activity_recommend.xml
  app/src/main/res/layout/item_recommend_bottom.xml
  app/src/main/res/layout/item_recommend_bottom_info.xml
  app/src/main/res/values/dimens_recommend.xml
  app/src/main/res/values/styles_recommend.xml
  app/src/main/res/xml/network_security_config.xml
Labels: 기능 추가, 뷰 구조, 새우버거가 함께 합니다.

#41 closed #38 스크랩 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/BaseApplication.kt
  app/src/main/java/hbs/com/picnic/content/ContentActivity.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ChattingUseCase.kt
  app/src/main/java/hbs/com/picnic/content/usecase/ContentUseCase.kt
  app/src/main/java/hbs/com/picnic/data/local/LocalRepository.kt
  app/src/main/java/hbs/com/picnic/data/model/Bookmark.kt
  app/src/main/java/hbs/com/picnic/remote/FcmRepository.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentViewContract.kt
  app/src/main/java/hbs/com/picnic/view/content/presenter/ContentViewPresenter.kt
  app/src/main/res/drawable/bg_bottom_sheet_gradient.xml
  app/src/main/res/drawable/bg_circle_white_radius.xml
  app/src/main/res/drawable/bg_send_chat_on.xml
  app/src/main/res/drawable/ic_arrow_down_black_24dp.xml
  app/src/main/res/drawable/ic_bookmark_off_24dp.xml
  app/src/main/res/drawable/ic_bookmark_on_24dp.xml
  app/src/main/res/drawable/ic_picnic.xml
  app/src/main/res/drawable/ic_share_24dp.xml
  app/src/main/res/layout/item_chatting_dialog.xml
  app/src/main/res/layout/item_your_chatting_dialog.xml
  app/src/main/res/layout/layout_bottom_sheet.xml
  app/src/main/res/layout/layout_coordinator_toolbar.xml
  app/src/main/res/layout/view_content.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 그래들, 기능 추가

#46 closed #45 투어 정보를 가져오는 로직 개선
  app/src/main/java/hbs/com/picnic/data/remote/TourRepository.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/RecommendContract.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/presenter/RecommendPresenter.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/usecase/RecommendUseCase.kt
  app/src/main/java/hbs/com/picnic/utils/BaseContract.kt
Labels: 읽어 봤으면 좋겠어요.

#47 closed #40 CSV 파일 연동
  app/src/main/assets/seoul_dduck.csv
  app/src/main/assets/seoul_foodtruck.csv
  app/src/main/assets/seoul_icecream.csv
  app/src/main/assets/seoul_kids.csv
  app/src/main/assets/seoul_market.csv
  app/src/main/assets/seoul_park.csv
  app/src/main/java/hbs/com/picnic/data/model/MenuInfo.kt
  app/src/main/java/hbs/com/picnic/data/model/ParkInfo.kt
  app/src/main/java/hbs/com/picnic/utils/MenuType.kt
  app/src/main/java/hbs/com/picnic/view/recommend/RecommendMenuContract.kt
  app/src/main/java/hbs/com/picnic/view/recommend/RecommendMenuView.kt
  app/src/main/java/hbs/com/picnic/view/recommend/adapter/RecommendMenuAdapter.kt
  app/src/main/java/hbs/com/picnic/view/recommend/presenter/RecommendMenuPresenter.kt
  app/src/main/java/hbs/com/picnic/view/recommend/presenter/RecommendViewPresenter.kt
  app/src/main/java/hbs/com/picnic/view/recommend/usecase/RecommendMenuUseCase.kt
  app/src/main/res/layout/item_recommend_row.xml
Labels: 기능 추가, 읽어 봤으면 좋겠어요.

#50 closed #49 스크랩 뷰 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/picnic/data/local/LocalRepository.kt
  app/src/main/java/hbs/com/picnic/data/model/ParkInfo.kt
  app/src/main/java/hbs/com/picnic/ui/bookmark/BookmarkActivity.kt
  app/src/main/java/hbs/com/picnic/ui/bookmark/BookmarkContract.kt
  app/src/main/java/hbs/com/picnic/ui/bookmark/adapter/BookmarkAdapter.kt
  app/src/main/java/hbs/com/picnic/ui/bookmark/presenter/BookmarkPresenter.kt
  app/src/main/java/hbs/com/picnic/ui/bookmark/usecase/BookmarkUseCase.kt
  app/src/main/java/hbs/com/picnic/view/recommend/usecase/RecommendMenuUseCase.kt
  app/src/main/res/drawable/bg_bookmark_gradient.xml
  app/src/main/res/layout/activity_bookmark.xml
  app/src/main/res/layout/item_scrap.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 뷰 구조, 새우버거가 함께 합니다.

#52 closed #48 Feature/issue 48
  app/src/main/java/hbs/com/picnic/data/model/TourInfo.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/RecommendContract.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/presenter/RecommendPresenter.kt
  app/src/main/java/hbs/com/picnic/ui/setting/SettingActivity.kt
  app/src/main/java/hbs/com/picnic/utils/CustomItemDecoration.kt
  app/src/main/java/hbs/com/picnic/utils/MenuType.kt
  app/src/main/java/hbs/com/picnic/utils/SharedManager.kt
  app/src/main/java/hbs/com/picnic/utils/TourType.kt
  app/src/main/java/hbs/com/picnic/utils/XmlParser.kt
  app/src/main/java/hbs/com/picnic/view/recommend/RecommendMenuView.kt
  app/src/main/java/hbs/com/picnic/view/recommend/adapter/RecommendBottomAdapter.kt
  app/src/main/java/hbs/com/picnic/view/recommend/presenter/RecommendMenuPresenter.kt
  app/src/main/res/drawable/ic_bookmark_menu.xml
  app/src/main/res/drawable/ic_bookmark_off.xml
  app/src/main/res/drawable/ic_bookmark_on.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_culture_color.xml
  app/src/main/res/drawable/ic_culture_line.xml
  app/src/main/res/drawable/ic_festival_color.xml
  app/src/main/res/drawable/ic_festival_line.xml
  app/src/main/res/drawable/ic_food_color.xml
  app/src/main/res/drawable/ic_food_line.xml
  app/src/main/res/drawable/ic_heart_color.xml
  app/src/main/res/drawable/ic_heart_white.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_ice_drop_line.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_palace_green_line.xml
  app/src/main/res/drawable/ic_place_pin.xml
  app/src/main/res/drawable/ic_setting_menu.xml
  app/src/main/res/drawable/ic_shopping_color.xml
  app/src/main/res/drawable/ic_shopping_line.xml
  app/src/main/res/drawable/ic_suitcase_color.xml
  app/src/main/res/drawable/ic_suitcase_line.xml
  app/src/main/res/drawable/ic_surf_color.xml
  app/src/main/res/drawable/ic_surf_line.xml
  app/src/main/res/drawable/ic_tour_color.xml
  app/src/main/res/drawable/ic_tour_line.xml
  app/src/main/res/drawable/ic_travel_color.xml
  app/src/main/res/drawable/selector_culture.xml
  app/src/main/res/drawable/selector_festival.xml
  app/src/main/res/drawable/selector_food.xml
  app/src/main/res/drawable/selector_reports.xml
  app/src/main/res/drawable/selector_shopping.xml
  app/src/main/res/drawable/selector_tour.xml
  app/src/main/res/drawable/selector_travel.xml
  app/src/main/res/layout/activity_recommend.xml
  app/src/main/res/layout/content_drawer.xml
  app/src/main/res/layout/content_drawer_menu.xml
  app/src/main/res/layout/content_recommend.xml
  app/src/main/res/layout/item_recommend_bottom.xml
  app/src/main/res/layout/item_recommend_bottom_info.xml
  app/src/main/res/layout/item_recommend_row.xml
  app/src/main/res/layout/view_drawer_menu.xml
  app/src/main/res/layout/view_recommend_menu.xml
  app/src/main/res/values/dimens_recommend.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/styles_recommend.xml
Labels: 기능 추가, 뷰 구조

#55 #closed 53 Feature/issue 53
  app/src/main/AndroidManifest.xml
  app/src/main/assets/loading_progress.json
  app/src/main/java/hbs/com/picnic/data/model/TourRequest.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/RecommendContract.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/presenter/RecommendPresenter.kt
  app/src/main/java/hbs/com/picnic/utils/SharedManager.kt
  app/src/main/java/hbs/com/picnic/utils/TourType.kt
  app/src/main/res/layout/content_recommend.xml
  app/src/main/res/layout/view_recommend_menu.xml
  app/src/main/res/values/dimens_recommend.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#60 closed #59 지도 마커 개선, 디테일 기능 로직 개선
  app/src/main/java/hbs/com/picnic/data/model/TourDetail.kt
  app/src/main/java/hbs/com/picnic/ui/map/MapActivity.kt
  app/src/main/java/hbs/com/picnic/ui/map/MapContract.kt
  app/src/main/java/hbs/com/picnic/ui/recommend/RecommendActivity.kt
  app/src/main/java/hbs/com/picnic/utils/BindingUtils.kt
  app/src/main/java/hbs/com/picnic/view/content/ContentView.kt
  app/src/main/java/hbs/com/picnic/view/content/adapter/ContentAdapter.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/content_drawer.xml
  app/src/main/res/layout/item_chatting_dialog.xml
  app/src/main/res/layout/item_content_content.xml
  app/src/main/res/layout/item_content_subcontent.xml
  app/src/main/res/layout/item_map.xml
  app/src/main/res/layout/item_subtitle.xml
  app/src/main/res/layout/layout_coordinator_toolbar.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 뷰 구조
